import { NextResponse } from "next/server";
import { requireRole } from "@/lib/api-auth";
import { prisma } from "@/lib/prisma";

type RouteContext = {
	params: Promise<{ userId: string }>;
};

const MAX_AVATAR_BYTES = 2_000_000;

export async function GET(_req: Request, context: RouteContext) {
	try {
		const { error, session } = await requireRole([
			"ADMIN",
			"SUPERVISOR",
			"PHARMACIST",
		]);
		if (error) return error;
		void session;

		const { userId } = await context.params;
		if (!/^[a-z0-9]{20,}$/.test(userId) && !/^cm[a-z0-9]+$/.test(userId)) {
			return NextResponse.json({ message: "Invalid user ID" }, { status: 400 });
		}

		const user = await prisma.user.findUnique({
			where: { id: userId },
			select: { image: true },
		});

		if (!user?.image) {
			return NextResponse.json({ message: "Avatar not found" }, { status: 404 });
		}

		const image = user.image;

		// Remote profile images (e.g. Google OAuth) are redirected as-is.
		if (/^https?:\/\//.test(image)) {
			return NextResponse.redirect(image, 302);
		}

		// Stored data URIs (generated by /api/account/profile-image) are served
		// directly so the app never has to embed megabytes of base64 in payloads.
		const match = /^data:(image\/[a-zA-Z0-9.+-]+);base64,([A-Za-z0-9+/=]+)$/.exec(
			image,
		);
		if (!match) {
			return NextResponse.json({ message: "Avatar not found" }, { status: 404 });
		}

		const [, contentType, base64] = match;
		const buffer = Buffer.from(base64, "base64");

		if (buffer.byteLength > MAX_AVATAR_BYTES) {
			return NextResponse.json({ message: "Avatar not found" }, { status: 404 });
		}

		return new NextResponse(new Uint8Array(buffer), {
			status: 200,
			headers: {
				"Content-Type": contentType,
				"Content-Length": String(buffer.byteLength),
				"Cache-Control": "private, max-age=3600",
				"Content-Disposition": "inline",
				"X-Content-Type-Options": "nosniff",
			},
		});
	} catch {
		return NextResponse.json({ message: "Avatar could not be loaded" }, { status: 500 });
	}
}